name: Setup Docker
description: Log in to AWS Docker container registry
inputs:
  registry:
    description: registry
    required: false
    default: 563565546264.dkr.ecr.eu-west-1.amazonaws.com
runs:
  using: composite
  steps:
    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
