name: Build output
description: Compress files, write comments about their sizes and publish them
inputs:
  files:
    description: 'One line per file that needs to be analyzed in the form <baseDir>@<regex> (regex is optional and shall match only one file)'
    required: true
runs:
  using: composite
  steps:
    - id: comment
      if: ${{ github.event_name == 'push' }}
      uses: pbstck/actions/build-output/comment@v1
      with:
        files: ${{ inputs.files }}
    - uses: pbstck/actions/build-output/publish@v1
      if: ${{ github.event.ref == 'refs/heads/main' && github.event_name == 'push' }}
      with:
        comments: "[${{join(steps.comment.outputs.*, ',')}}]"
