name: setup pnpm action
description: Install pnpm with the desired version and cache its directory
inputs:
  node-version:
    description: 'version'
    required: false
  private-pull:
    description: "Allow private pull"
    required: false
    default: "false"
  run_install:
    description: Run pnpm install
    required: false
    default: "true"
  working-directory:
    description: "The working directory this action should operate in"
    required: false
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
       package_json_file: ${{ inputs.working-directory || '.' }}/package.json
    - name: Use Node.js ${{ inputs.node-version || env.NODE_VERSION || '18.x' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version || env.NODE_VERSION || '18.x' }}
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.working-directory || '.' }}/pnpm-lock.yaml
    - name: Install dependencies
      if: ${{ inputs.run_install == 'true' }}
      run: pnpm install --frozen-lockfile
      shell: bash
      working-directory: ${{ inputs.working-directory || '.' }}

