name: Login AWS
description: Login to AWS CLI
inputs:
  aws-region:
    description: 'aws-region'
    required: false
  role-to-assume:
    description: 'AWS Role to assume by Github action'
    required: false
runs:
  using: "composite"
  steps:
    - name: Configure AWS with key and secret
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ !inputs.role-to-assume && !env.AWS_GH_ACTION_ROLE }}
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-west-1"
    - name: Configure AWS with assume role
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.role-to-assume || env.AWS_GH_ACTION_ROLE }}
      with:
        aws-region: ${{ inputs.aws-region || env.AWS_DEFAULT_REGION || 'eu-west-1' }}
        role-to-assume: ${{ inputs.role-to-assume || env.AWS_GH_ACTION_ROLE }}
