name: Continuous integration
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      coverage:
        required: false
        type: boolean
        default: false
      build:
        required: false
        type: boolean
        default: true
      go-version:
        required: false
        type: string
        default: '1.18'
env:
  WORKING_DIRECTORY: "code/go"
  AWS_DEFAULT_REGION: "eu-west-1"
  AWS_GH_ACTION_ROLE: ${{ vars.TOOL_GH_ACTION_ROLE_ARN }}
  GOPRIVATE: github.com/pbstck
  MODELS_SECRET_KEY: ${{ secrets.MODELS_SECRET_KEY }}
  GO_VERSION: ${{ inputs.go-version }}
permissions:
  id-token: write # required to use OIDC authentication
  contents: write # read is required for actions/checkout, write is required for pbstck/actions/coverage to be able to write comments on commits (on main)
  pull-requests: write # write is required to let pbstck/actions/coverage write comments on PR
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: pbstck/actions/setup-go@v1
        with:
          private-pull: true
      - run: go get ./...
  test:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: pbstck/actions/setup-task@v1
      - name: Setup Go
        uses: pbstck/actions/setup-go@v1
        with:
          private-pull: true
      - name: Test
        run: |
          if ${{ inputs.coverage }} ; then
            task -y ${{inputs.project}}:test/coverage
          else
            task -y ${{inputs.project}}:test
          fi
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.coverage == true }}
        with:
          name: coverage_${{ inputs.project }}
          path: '**/*/total-statements-coverage'
  lint:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: pbstck/actions/setup-task@v1
      - name: Setup Go
        uses: pbstck/actions/setup-go@v1
        with:
          private-pull: true
      - name: Lint
        run: task -y ${{inputs.project}}:lint/check
  build:
    if: ${{ inputs.build == true }}
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: pbstck/actions/setup-task@v1
      - name: Setup Go
        uses: pbstck/actions/setup-go@v1
        with:
          private-pull: true
      - name: Build
        run: task -y ${{inputs.project}}:build
      - uses: actions/upload-artifact@v4
        if: ${{ github.event.ref == 'refs/heads/main' }}
        with:
          name: binary_${{ inputs.project }}
          path: bin/*.zip
